#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "AIoT_Precision_Logger_Cloud_Demo"
  https://create.arduino.cc/cloud/things/7b8db3c1-f3cd-4739-8153-07ccd6352eb7 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float Current;
  float pcbTemperature;
  float tcVoltage;
  float Temperature;
  float TemperatureF;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "KTypeTC.h" //Local library for handling thermocouple math
#include <ADS126X.h> //external library that you need to add for ADC
#include <FastLED.h> //external library you need to add for controlling RGB LED

//ADC settings
#define ADC1_BITS (float)2147483647.0 //this is for 31 bits with the 32nd bit being signed
#define VREF_2048 (float)2.048 //optional Ext reference voltage
#define VREF_INT (float)2.5 //internal ref voltage
#define SHUNT_RESISTOR (float)0.1 //value of shunt resistor
#define PGA_BYPASSED   0b101 //created this value that is not in the library, so you know if we want PGA bypassed
//Volt reference
#define INT_2_5_VREF 0
#define EXT_2048_VREF 1
//RGB LED constants
#define NUM_LEDS 1 //num of RGB LEDs
#define DATA_PIN 1 //GPIO LED is connected to
#define ANABIT_BLUE 0x00CCFF //Anabit's colors :-)
#define ANABIT_YELLOW 0xFFCC00
#define ANABIT_PINK 0xFF66FF

CRGB leds[NUM_LEDS]; //declare LED object and initialize with LED count
uint32_t ledColor = ANABIT_BLUE; //tracks LED color 
ADS126X adc; // start the class
const uint8_t cSelect = 10; //chip select pin for SPI comm, this is required by the sketch to work correctly
float iConvTime = 0; //holds time (in msec) it takes to complete measurement conversion, calcualted at run time based on ADC settings
float tConvTime = 0; //holds time in msec to complete thermocouple measurement
float tcConvTime = 0; //holds measurement time delay for thermocouple measurements

//structure to hold all the ADC settings for the thermocouple measurement
struct PrecisionLoggerSettings{ 
    uint8_t posMeasPin = ADS126X_AIN6; //sets positive measurement channel / pin 
    uint8_t negMeasPin = ADS126X_AIN7; //sets negative measurement channel / pin, for single ended measurements tie this pin to ground
    uint8_t sampleRateSetting = ADS126X_RATE_2_5;    // Sample rate in samples per second
    uint8_t filterType = ADS126X_SINC1; //See library file ADS126X_definitions.h for constnat to set filter type
    uint8_t progGainAmp = ADS126X_GAIN_32; //determines amp gain and allows you to bypass amp (default)
    uint8_t vRef = INT_2_5_VREF; //set voltage reference to internal
    bool choppingEnabled = false;  // Chopping Mode helps improve measurement accuracy but at the cost of more measurement time
    bool iDACRotation = false; //applicable when using current source, increases IDAC accuracy but doubles measurement time
} tcSensorConfig;

PrecisionLoggerSettings tempSensorConfig; //structure to hold settings for internal temperature sensor measurement (cold junction measurement)
PrecisionLoggerSettings iShuntConfig; //structure to hold settings for current shunt / sense resistor measurements

void setup() {
  leds[0] = ledColor; //set LED RGB color
  FastLED.addLeds<WS2812,DATA_PIN,RGB>(leds,NUM_LEDS); //add LED 
  FastLED.setBrightness(84); //set LED brightness
  FastLED.show();  //turn on LED
  //establish settings for cold junction (internal temp sensor) measurements
  tempSensorConfig.posMeasPin = ADS126X_TEMP; //set mux to internal temp sensor
  tempSensorConfig.negMeasPin = ADS126X_TEMP; //set mux to internal temp sensor
  tempSensorConfig.sampleRateSetting = ADS126X_RATE_2_5;
  tempSensorConfig.filterType = ADS126X_SINC1; //See library file ADS126X_definitions.h for constnat to set filter type
  tempSensorConfig.progGainAmp = ADS126X_GAIN_1; //for internal temp sensor PGA must be on with gain of 1 as per datasheet
  tempSensorConfig.vRef = INT_2_5_VREF; //set refernce used for measurement
  tempSensorConfig.choppingEnabled = false; //chop mode can not be used for internal temp sensor measurements as per datasheet
  tempSensorConfig.iDACRotation = false; //only applicable when using internal current sources (IDAC)
  //establish settings for current (shunt resistor) measurements
  iShuntConfig.posMeasPin = ADS126X_AIN4; //set mux to AIN4+
  iShuntConfig.negMeasPin = ADS126X_AIN5; //set mux to AIN5-
  iShuntConfig.sampleRateSetting = ADS126X_RATE_2_5;
  iShuntConfig.filterType = ADS126X_SINC1; //See library file ADS126X_definitions.h for constnat to set filter type
  iShuntConfig.progGainAmp = ADS126X_GAIN_8; //PGA gain setting
  iShuntConfig.vRef = INT_2_5_VREF; //set refernce used for measurement
  iShuntConfig.choppingEnabled = false; //chop mode can not be used for internal temp sensor measurements as per datasheet
  iShuntConfig.iDACRotation = false; //only applicable when using internal current sources (IDAC)

  //lets get ADC conversion time for thermo couple measurement
  iConvTime = calculateADS1262Timing(iShuntConfig); //based on filter, sample rate, and chop mode calculated measurement conversion time
  tConvTime = calculateADS1262Timing(tempSensorConfig); //based on filter, sample rate, and chop mode calculated measurement conversion time
  tcConvTime = calculateADS1262Timing(tcSensorConfig); //based on filter, sample rate, and chop mode calculated measurement conversion time
  Serial.begin(9600);
  adc.begin(cSelect); // setup with chip select pin, required by ADC library. ADC library starts SPI communication using default settings 
  // Defined in thingProperties.h
  initProperties();
  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  //first we will get thermocouple measurement
  initLogger(tcSensorConfig); //init ADC settings with thermocouple measurement config
  discardFirstReadingDelayConTime(tcConvTime,tcSensorConfig.posMeasPin,tcSensorConfig.negMeasPin); //when ADC mux is changed have to discard first reading
  delay(tcConvTime); //delay to let next conversion complete
  int32_t code =   aDC1Measurement(tcSensorConfig.posMeasPin,tcSensorConfig.negMeasPin); //get ADC1 measurement
  float vTemp =    getADCtoVoltage(code,ADC1_BITS,tcSensorConfig.vRef); //get voltage from ADC reading
  tcVoltage = scaleVoltMeas4Gain(vTemp, tcSensorConfig.progGainAmp); //adjust voltage based on PGA setting
  Serial.print("Measured thermocouple voltage: "); Serial.println(tcVoltage,6); // send voltage through serial
  //next we get the cold reference temperature measurement
  initLogger(tempSensorConfig); //reset ADC settings for temp sensor measurement
  discardFirstReadingDelayConTime(tConvTime,tempSensorConfig.posMeasPin, tempSensorConfig.negMeasPin); //burn first ADC measurement
  delay(tConvTime); //delay to let next conversion complete
  code =   aDC1Measurement(tempSensorConfig.posMeasPin,tempSensorConfig.negMeasPin); //get ADC1 measurement of internal temperature sensor
  float tTemp =    getADCtoVoltage(code,ADC1_BITS,tempSensorConfig.vRef); //get voltage from ADC reading
  tTemp = scaleVoltMeas4Gain(tTemp, tempSensorConfig.progGainAmp); //adjust voltage based on PGA setting
  pcbTemperature = convertVolt2IntTemperatureVal(tTemp); //convert volt measurement to temperature
  Serial.print("Temperture internal sensor value: "); Serial.println(pcbTemperature,2); // send voltage through serial
  //finally we use our two measurements to calculate the measured K-type thermocouple temperature
  vTemp = vTemp*1000; //convert voltage measurement to millivolts
  Temperature = KTypeTC::temperature(vTemp,pcbTemperature);  //calculate K-Type thermocouple temperature value
  TemperatureF = celsiusToFahrenheit(Temperature); //get temp in F

    if (isnan(Temperature))
        Serial.println(F("Measured temperature value is out of range"));
    else {
        Serial.print(F("Measured K-Type Thermocouple temperature degrees C: ")), Serial.println(Current, 2);
        Serial.print(F("Measured K-Type Thermocouple temperature degrees F: ")), Serial.println(celsiusToFahrenheit(Current), 2);
    }
  //make current measurement from shunt resistor
  initLogger(iShuntConfig); //init ADC settings with thermocouple measurement config
  discardFirstReadingDelayConTime(iConvTime,iShuntConfig.posMeasPin,iShuntConfig.negMeasPin); //when ADC mux is changed have to discard first reading
  delay(iConvTime); //delay to let next conversion complete
  code =   aDC1Measurement(iShuntConfig.posMeasPin,iShuntConfig.negMeasPin); //get ADC1 measurement
  vTemp =    getADCtoVoltage(code,ADC1_BITS,iShuntConfig.vRef); //get voltage from ADC reading
  vTemp = scaleVoltMeas4Gain(vTemp, iShuntConfig.progGainAmp); //adjust voltage based on PGA setting
  Current = calculateCurrent(vTemp); //calculate current based on measured voltage across shunt resistor
  Serial.print("Measured shunt resistor current: "); Serial.println(Current,4); // send voltage through serial

  //if else statement to toggle LED color
  if(ledColor == ANABIT_BLUE) ledColor = ANABIT_YELLOW;
  else if(ledColor == ANABIT_YELLOW) ledColor = ANABIT_PINK;
  else ledColor = ANABIT_BLUE;
  leds[0] = ledColor; //set LED RGB color
  FastLED.show();  //turn on LED
}

//this function takes a voltage measurement from the internal temperature
//and converts it to a temperature measurement in C. This function uses the
//algorithm found in the datasheet page 35:
//Temperature (°C) = [(Temperature Reading (µV) – 122,400) / 420 µV/°C] + 25°C 
//volt values are in micro volts
//note that datasheet says self heating of ADC IC can lead to 0.7 degree error compared to PCB
float convertVolt2IntTemperatureVal(float tVolt) {
  tVolt = tVolt*1000000; //convert volts to micro volts
  return (((tVolt - 122400)/420) + 25);
}

// Convert Celsius to Fahrenheit
float celsiusToFahrenheit(float tempC) {
  float tempF = (tempC * 9.0 / 5.0) + 32.0;
  return tempF;
}


//This function starts ADC1 (stops it first), delays for conversion time, 
//and clears buffer by disgarding first reading
//Input argument is ADC conversion time
void discardFirstReadingDelayConTime(float cTime, uint8_t posChan, uint8_t negChan) {
  adc.stopADC1(); //stop ADC 1
  adc.startADC1(); // start conversion on ADC1
  delay(cTime); //delay conversion time
  adc.readADC1(posChan,negChan); //burn first reading to clear buffer
}

//converts ADC reading to voltage, voltage is returned as float
//input arguments are measured ADC value, ADC resolution, ADC ref voltage, volt measurement range
float getADCtoVoltage(int32_t aVal,float bits, uint8_t rVoltSetting) {
  float vRef;
  if(rVoltSetting == INT_2_5_VREF) vRef = VREF_INT; //use internal ref value
  else vRef = VREF_2048;
  return (((float)aVal / bits) * vRef);
}


//function to scale voltage value based on the PGA setting and gain
//input argument is measured voltage value and PGA gain we are in
//returns voltage value based on gain we are in
float scaleVoltMeas4Gain(float vVal, uint8_t gain) {
  float gainFactor;    
  if(gain == ADS126X_GAIN_1 || gain == PGA_BYPASSED) gainFactor = 1; 
  else if(gain == ADS126X_GAIN_2) gainFactor = 2; 
  else if(gain == ADS126X_GAIN_4) gainFactor = 4; 
  else if(gain == ADS126X_GAIN_8) gainFactor = 8; 
  else if(gain == ADS126X_GAIN_16) gainFactor = 16; 
  else gainFactor = 32; 
  return vVal/gainFactor; 
}

//calculates current based on measured voltage and known shunt resistor value
//returns calculated current through sense / shunt resistor
float calculateCurrent(float measuredVoltage) {
  return measuredVoltage / SHUNT_RESISTOR; 
}

//settings for ADC1 PGA, allows you to enable or disable and sets gain
//input argument true for enable or false for disable.
//second argument sets gain. If disabled, gain setting is ignored
void setADC1PGA(uint8_t gain) {
  if(gain == PGA_BYPASSED) adc.bypassPGA(); //do not use PGA
  else {
    adc.enablePGA(); //use PGA
    adc.setGain(gain); //set gain of PGA
  }
}

//set voltage reference, input argument is vref you want to use
//For the external ref pins are hard coded, if you have the external ref option be sure the DIP switches are set correctly
void setsUpADCVoltRef(uint8_t voltRef) {
  adc.enableInternalReference(); //turn on internal reference, needed for IDACs
  if(voltRef == INT_2_5_VREF) adc.setReference(ADS126X_REF_NEG_INT, ADS126X_REF_POS_INT); //use internal ref
  else adc.setReference(ADS126X_REF_NEG_AIN1, ADS126X_REF_POS_AIN0); //Set this up based on DIP switch settings, AIN3 tied to analog ground and AIN0 to 2.048V ref
}

//this function sets up the ADC settings
//input argument is the structure with ADC settings
void initLogger(PrecisionLoggerSettings loggerSettings) {
  setsUpADCVoltRef(loggerSettings.vRef); //turn on internal ref and select between int and ext
  setADC1PGA(loggerSettings.progGainAmp); //set default range of meter
  //give time for voltage reference to settle
  delay(10); //give current source and ref time to settle
  //adc.calibrateSelfOffsetADC1(); //do internal offset calibration
  if(loggerSettings.choppingEnabled && loggerSettings.iDACRotation) adc.setChopMode(ADS126X_CHOP_3); //11 enables both chop mode and IDAC rotation
  else if(loggerSettings.choppingEnabled)  adc.setChopMode(ADS126X_CHOP_1); //01 enable chop mode, IDAC is off
  else if(loggerSettings.iDACRotation)  adc.setChopMode(ADS126X_CHOP_2); //10 enable IDAC rotation, not chop mode
  else adc.setChopMode(ADS126X_CHOP_0); //00 disable chop mode and IDAC rotation
  adc.setFilter(loggerSettings.filterType); //set ADC1 filter type ADS126X_SINC4
  adc.setRate(loggerSettings.sampleRateSetting); //sets ADC sample rate ADS126X_RATE_2_5
  adc.clearResetBit(); //clear reset bit if it is set
}

int32_t aDC1Measurement(uint8_t posMeasChan, uint8_t negMeasChan) {
  return adc.readADC1(posMeasChan,negMeasChan); //make ADC1 measurement
}

// Function to compute conversion and settling time in milliseconds of ADC1
//input arguments include filter type (reg), data rate (reg), is chop mode enabled
//returns conversion time in milliseconds 
float calculateADS1262Timing(PrecisionLoggerSettings loggerSettings) {
  uint8_t settlingFactor;
  float sampleRate;

  // Identify settling factor for each filter
  switch (loggerSettings.filterType) {
    case ADS126X_FIR:
      settlingFactor = 3;
      break;
    case ADS126X_SINC1:
      settlingFactor = 1;
      break;
    case ADS126X_SINC2:
      settlingFactor = 2;
      break;
    case ADS126X_SINC3:
      settlingFactor = 3;
      break;
    case ADS126X_SINC4:
      settlingFactor = 4;
      break;
    default:
      settlingFactor = 4; //invalid filter type so set to highest settling factor
      break;
  }

   //get sample rate value
  switch (loggerSettings.sampleRateSetting) {
    case ADS126X_RATE_2_5:
      sampleRate = 2.5;
      break;
    case ADS126X_RATE_5:
      sampleRate = 5.0;
      break;
    case ADS126X_RATE_10:
      sampleRate = 10.0;
      break;
    case ADS126X_RATE_16_6:
      sampleRate = 16.6;
      break;
    case ADS126X_RATE_20:
      sampleRate = 20.0;
      break;
    case ADS126X_RATE_50:
      sampleRate = 50.0;
      break;
    case ADS126X_RATE_60:
      sampleRate = 60.0;
      break;
    case ADS126X_RATE_100:
      sampleRate = 100.0;
      break;
    case ADS126X_RATE_400:
      sampleRate = 400.0;
      break;
    case ADS126X_RATE_1200:
      sampleRate = 1200.0;
      break;
    case ADS126X_RATE_2400:
      sampleRate = 2400.0;
      break;
    case ADS126X_RATE_4800:
      sampleRate = 4800.0;
      break;
    case ADS126X_RATE_7200:
      sampleRate = 7200.0;
      break;
    case ADS126X_RATE_14400:
      sampleRate = 14400.0;
      break;
    case ADS126X_RATE_19200:
      sampleRate = 19200.0;
      break;
    case ADS126X_RATE_38400:
      sampleRate = 38400.0;
      break;
    default:
      sampleRate = 2.5; //invalid filter type so set to highest settling factor
      break;
  }

  float Tconv_ms = 1000.0 / sampleRate;  // Base conversion period in ms

  // Calculate settling time
  //there is a ~400usec delay at any filter setting beyond the conversion rate
  Tconv_ms = (Tconv_ms * settlingFactor) + 1; //add one because most filters have a ~400usec delay

  // Double conversion period if chopping mode is enabled
  if (loggerSettings.choppingEnabled) {
    Tconv_ms *= 2.0;  // Chopping mode A doubles conversion time
  } 
  //double conversion period if IDAC rotation mode is enabled
  if (loggerSettings.iDACRotation) {
    Tconv_ms *= 2.0;  // Chopping mode A doubles conversion time
  } 

  return Tconv_ms; //return delay time between measurements
}

/*
  Since Current is READ_WRITE variable, onCurrentChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCurrentChange()  {
  // Add your code here to act upon Current change
}
/*
  Since Temperature is READ_WRITE variable, onTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureChange()  {
  // Add your code here to act upon Temperature change
}
/*
  Since PcbTemperature is READ_WRITE variable, onPcbTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPcbTemperatureChange()  {
  // Add your code here to act upon PcbTemperature change
}

/*
  Since TemperatureF is READ_WRITE variable, onTemperatureFChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureFChange()  {
  // Add your code here to act upon TemperatureF change
}


/*
  Since TcVoltage is READ_WRITE variable, onTcVoltageChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTcVoltageChange()  {
  // Add your code here to act upon TcVoltage change
}