// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "9832e9ef-a81e-4c05-9ed7-040bca1919bb";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCurrentChange();
void onPcbTemperatureChange();
void onTcVoltageChange();
void onTemperatureChange();
void onTemperatureFChange();

float Current;
float pcbTemperature;
float tcVoltage;
float Temperature;
float TemperatureF;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(Current, READWRITE, ON_CHANGE, onCurrentChange);
  ArduinoCloud.addProperty(pcbTemperature, READWRITE, ON_CHANGE, onPcbTemperatureChange);
  ArduinoCloud.addProperty(tcVoltage, READWRITE, ON_CHANGE, onTcVoltageChange);
  ArduinoCloud.addProperty(Temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(TemperatureF, READWRITE, ON_CHANGE, onTemperatureFChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
